version: 2.2.0.{build}

shallow_clone: true

image: Visual Studio 2017

platform: x64

cache:
  - msvc\opt -> deposit.mk, msvc\Makefile
  - msvc\src -> deposit.mk, msvc\Makefile
  - msvc\tmp -> deposit.mk, msvc\Makefile
  - msvc\var -> deposit.mk, msvc\Makefile

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

install:
  - 'C:\cygwin64\setup-x86_64.exe -d -n -N -q -P m4,make,patch,tar,unzip,wget'

build_script:
  - 'C:\cygwin64\bin\bash -l -c "cd $(cygpath $APPVEYOR_BUILD_FOLDER)/msvc && cp config.mk.x86-64 config.mk && make"'
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - cd %APPVEYOR_BUILD_FOLDER%\msvc && msbuild all.proj
