sudo: false
dist: trusty

language: cpp

os:
  - linux
  # - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - libtool
    - gcc-4.9
    - g++-4.9
    - clang-4.0
    - libgtk2.0-dev
    - libxml2-dev
    - uuid-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install ant; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install pkg-config; fi

install:
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "g++" ]; then export CC="gcc-4.9" CXX="g++-4.9" CFLAGS="-g0 -O0" CXXFLAGS="-g0 -O0"; fi
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "clang++" ]; then export CC="clang-4.0" CXX="clang++-4.0" CFLAGS="-g0 -O0" CXXFLAGS="-g0 -O0"; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then cd posix; else cd xcode; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then echo "PKG_CONFIG = /usr/local/bin/pkg-config" > config.mk; fi
  - travis_wait 60 make -s

script:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then make check; else make; fi # in posix/ or xcode/
