version: ~> 1.0

arch:
  - amd64
  - arm64

dist: xenial

language: cpp

os:
  - linux
  # - osx

osx_image: xcode11.2

cache:
  directories:
  - posix/src
  - xcode/src

env:
  global:
    - MAKEFLAGS="-j 2"

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libgtk2.0-dev
    - libsqlite3-dev
    - uuid-dev

install:
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "g++" ]; then export CFLAGS="-g0 -O0" CXXFLAGS="-g0 -O0"; fi
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "clang++" ]; then export CFLAGS="-g0 -O0" CXXFLAGS="-g0 -O0"; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then cd posix; else cd xcode; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export LIBTOOL=glibtool LIBTOOLIZE=glibtoolize; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then cp config.mk.travis config.mk; fi
  - make -s download
  - travis_wait 60 make -s external
  - make -s all

script:
  - make check # in posix/ or xcode/
